### PR TITLE
Fix analysis issues in shell and Rust

### LINKED ISSUE #73: [BUG] Fix analysis issues in shell and Rust detected by DeepSource CI
**Describe the bug**

See the problems in DeepSource: https://deepsource.io/gh/eunomia-bpf/eunomia-bpf

The CI should pass when there is no issue found.

### PR DESCRIPTION
**Pull request by ocfox**
## Description
fix #73

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

File: ecli/ecli-rs/src/oci/wasm/mod.rs [hunk 1]
```diff
@@ -31,7 +31,7 @@ pub fn parse_img_url(url: &str) -> EcliResult<(Client, RegistryAuth, Reference,
             RegistryAuth::Basic(username, password)
         }
         Err(err) => {
-            if let EcliError::LoginInfoNotFoundError(_) = err {
+            if matches!(err, EcliError::LoginInfoNotFoundError(_)) {
```
Comment (ocfox) [inline ecli/ecli-rs/src/oci/wasm/mod.rs:34]: Not sure that this change is necessary, but on deepsource.

Comment (yunwei37) [reply ecli/ecli-rs/src/oci/wasm/mod.rs:34]: Well, maybe the next time we can disable b some unnecessary linters...

Comment (ocfox) [reply ecli/ecli-rs/src/oci/wasm/mod.rs:34]: And do I need squash for these commits?
